[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_counter = "861GJUxfTPw52zodfsUyfMDHVmv7iyZRqUitvnjVDz6Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/yash/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
